import pygame
from ball import Ball
#Primero hay que inicializar el entorno...
#Definimos el ancho y el alto de la ventanta...
ancho = 800
alto = 800
pygame.init() #inicializamos pygame...
screen = pygame.display.set_mode((ancho, alto)) #creamos la ventana...
clock = pygame.time.Clock() #creamos el reloj para controlar la animación...
el_framerate = 30 #Decidimos la cantidad de cuadros por segundo para la animación...
running = True #Variable para poder parar el juego...

#Creamos una pelota...
ball = Ball(30, pygame.Color(160,70,190), pygame.Vector2(50,750), pygame.Vector2(0,0), pygame.Vector2(0,0))

#Definimos nuestros colores...
fondo = pygame.Color(20,20,20) #Valores para rojo, verde y azul (0-255)...

#Ahora trabajamos en nuestro bucle principal...
while running: #Mientras running sea True vamos a repetir lo que sigue...

    #Vamos a consultar los eventos que ocurren durante una iteración del bucle...
    for event in pygame.event.get():
        if event.type == pygame.QUIT: #Si alguien cierra la ventana...
            running = False #Al terminar esta iteración el bucle se termina...

    #Tapamos el cuadro anterior con el color de fondo...
    screen.fill(fondo)

    #Chequeamos si el usuario toca alguna tecla...
    keys = pygame.key.get_pressed()
    if keys[pygame.K_UP]:
        #Hacemos saltar la pelota...
        ball.accelerate([0, 1])
        ball.set_speed([0,-30])
    if keys[pygame.K_RIGHT]:
        #Movemos la pelota a la derecha...
        ball.set_speed_x(5)
    if keys[pygame.K_LEFT]:
        #Movemos la pelota a la izquierda...
        ball.set_speed_x(-5)

    #Actualizamos la pelota...
    ball.update()
    
    #Si la pelota toca el piso la frenamos...
    if ball.position[1] >= alto - ball.size*2:
        ball.accelerate([0,0])
        ball.set_speed([0,0])

    #Ahora la dibujamos...
    pygame.draw.circle(screen, ball.color, ball.position, ball.size)

    #Actualizamos la pantalla, esta función es necesaria:
    pygame.display.flip()

    #Establecemos una velocidad de reproducción FPS.
    #Como el reloj cuenta en milisegundos dividimos 1000ms por el framerate:
    clock.tick(1000 / el_framerate)

#Si salimos del bucle while cerramos pygame:
pygame.quit()
